[0m01:10:02.777481 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000228C54771D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000228C4EC4250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000228C5289C10>]}


============================== 01:10:02.795359 | 12d62c0a-a5fc-43a4-a599-ff98732b7aa0 ==============================
[0m01:10:02.795359 [info ] [MainThread]: Running with dbt=1.7.19
[0m01:10:02.804470 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\LENOVO\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt init sales_analytics', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m01:10:02.811482 [debug] [MainThread]: Starter project path: c:\Users\LENOVO\OneDrive\Desktop\sales-analytics-pipeline\venv\Lib\site-packages\dbt\include\starter_project
[0m01:10:02.935111 [info ] [MainThread]: 
Your new dbt project "sales_analytics" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m01:10:02.940490 [info ] [MainThread]: Setting up your profile.
[0m01:14:56.641991 [info ] [MainThread]: Profile sales_analytics written to C:\Users\LENOVO\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m01:14:56.682335 [debug] [MainThread]: Command `dbt init` succeeded at 01:14:56.644487 after 294.08 seconds
[0m01:14:56.685870 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000228D4B4C190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000228D4C18650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000228D4AEF550>]}
[0m01:14:56.687960 [debug] [MainThread]: Flushing usage events
[0m21:30:37.457136 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D5CB624C50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D5CB667A10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D5CB617FD0>]}


============================== 21:30:37.466528 | a3c77085-4b2c-45f2-af1a-abe9ede3d592 ==============================
[0m21:30:37.466528 [info ] [MainThread]: Running with dbt=1.7.19
[0m21:30:37.468688 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\LENOVO\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m21:30:37.469818 [info ] [MainThread]: dbt version: 1.7.19
[0m21:30:37.472403 [info ] [MainThread]: python version: 3.11.5
[0m21:30:37.473956 [info ] [MainThread]: python path: c:\Users\LENOVO\OneDrive\Desktop\sales-analytics-pipeline\venv\Scripts\python.exe
[0m21:30:37.475524 [info ] [MainThread]: os info: Windows-10-10.0.22631-SP0
[0m21:30:43.868620 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.postgres'
[0m21:30:43.884247 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.postgres'
[0m21:30:43.884247 [info ] [MainThread]: Using profiles dir at C:\Users\LENOVO\.dbt
[0m21:30:43.884247 [info ] [MainThread]: Using profiles.yml file at C:\Users\LENOVO\.dbt\profiles.yml
[0m21:30:43.895980 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\LENOVO\OneDrive\Desktop\sales-analytics-pipeline\dbt_project.yml
[0m21:30:43.898083 [info ] [MainThread]: Configuration:
[0m21:30:43.899668 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m21:30:43.901185 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m21:30:43.902505 [info ] [MainThread]: Required dependencies:
[0m21:30:43.905218 [debug] [MainThread]: Executing "git --help"
[0m21:30:44.005790 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--config-env=<name>=<envvar>] <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m21:30:44.006803 [debug] [MainThread]: STDERR: "b''"
[0m21:30:44.009542 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m21:30:44.010019 [info ] [MainThread]: Connection test skipped since no profile was found
[0m21:30:44.013171 [info ] [MainThread]: [31m2 checks failed:[0m
[0m21:30:44.013171 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "deaf", target "dev" invalid: Runtime Error
    Could not find adapter type postgres!

Runtime Error
  Credentials in profile "modern_warehouse", target "dev" invalid: Runtime Error
    Could not find adapter type postgres!


[0m21:30:44.016493 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\LENOVO\OneDrive\Desktop\sales-analytics-pipeline\dbt_project.yml> not found

[0m21:30:44.021660 [debug] [MainThread]: Command `dbt debug` failed at 21:30:44.020416 after 6.75 seconds
[0m21:30:44.023702 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D5CB6573D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D5C4524D10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001D5CAFA8A90>]}
[0m21:30:44.025588 [debug] [MainThread]: Flushing usage events
[0m21:35:26.534757 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E18EE277D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E18EBF9DD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E18EDCF190>]}


============================== 21:35:26.540643 | 3fe97a60-ac9a-45ac-a467-49e078be7bec ==============================
[0m21:35:26.540643 [info ] [MainThread]: Running with dbt=1.7.19
[0m21:35:26.542650 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\LENOVO\\.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --models stg__product_review', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m21:35:26.543649 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\LENOVO\OneDrive\Desktop\sales-analytics-pipeline\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m21:35:26.548673 [debug] [MainThread]: Command `dbt run` failed at 21:35:26.547655 after 0.12 seconds
[0m21:35:26.550383 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E18EE07B50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E18E8B7E10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001E18E8B7910>]}
[0m21:35:26.553334 [debug] [MainThread]: Flushing usage events
